"""Send the daily briefing as an HTML email via Gmail SMTP.

Uses an App Password (not your main Gmail password).
Generate one at: https://myaccount.google.com/apppasswords
Requires GMAIL_ADDRESS and GMAIL_APP_PASSWORD in the environment.
"""

import os
import smtplib
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

_WRAPPER_STYLE = """
    body {
        font-family: Georgia, 'Times New Roman', serif;
        max-width: 780px;
        margin: 0 auto;
        padding: 24px;
        color: #1a1a1a;
        background: #ffffff;
        font-size: 15px;
        line-height: 1.6;
    }
    h1 {
        font-size: 20px;
        color: #1a1a1a;
        border-bottom: 2px solid #1a1a1a;
        padding-bottom: 8px;
        margin-bottom: 24px;
    }
    h2 {
        font-size: 16px;
        color: #1a1a1a;
        text-transform: uppercase;
        letter-spacing: 0.08em;
        border-left: 3px solid #c0392b;
        padding-left: 10px;
        margin-top: 32px;
        margin-bottom: 16px;
    }
    .story {
        margin-bottom: 20px;
        padding-bottom: 16px;
        border-bottom: 1px solid #e8e8e8;
    }
    .story:last-child { border-bottom: none; }
    a { color: #1a5276; text-decoration: none; }
    a:hover { text-decoration: underline; }
    em { color: #666; }
    .footer {
        margin-top: 40px;
        padding-top: 16px;
        border-top: 1px solid #ccc;
        font-size: 12px;
        color: #888;
    }
"""


def _wrap_html(body_html: str, today: date) -> str:
    date_str = today.strftime("%A, %B %-d, %Y")
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>{_WRAPPER_STYLE}</style>
</head>
<body>
<h1>Daily Briefing &mdash; {date_str}</h1>
{body_html}
<div class="footer">
  Generated by your Daily News Agent &bull; {date_str}
</div>
</body>
</html>"""


def send_email(html_body: str, today: date | None = None) -> None:
    """Send the HTML briefing email."""
    if today is None:
        today = date.today()

    sender = os.environ["GMAIL_ADDRESS"]
    recipient = os.environ.get("RECIPIENT_EMAIL", sender)
    password = os.environ["GMAIL_APP_PASSWORD"]

    subject = f"Daily Briefing — {today.strftime('%b %-d, %Y')}"
    full_html = _wrap_html(html_body, today)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = recipient
    msg.attach(MIMEText(full_html, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(sender, password)
        server.sendmail(sender, recipient, msg.as_string())

    print(f"[email] Sent '{subject}' to {recipient}")
